#!/bin/bash
# Kegberry install script.
# Replicates the full kegberry deployment on a fresh Raspberry Pi.
#
# Usage (fresh Pi, one-liner):
#   curl -sSL https://raw.githubusercontent.com/flangelo/kegberry/master/install.sh | bash
#
# Usage (if repo is already cloned to ~/kegberry):
#   bash ~/kegberry/install.sh

set -e

KEGBERRY_REPO="https://github.com/flangelo/kegberry.git"
KEGBERRY_DIR="$HOME/kegberry"
KEGBOT_DATA_DIR="/home/kegbot/kegbot-data"
ENV_FILE="${KEGBERRY_DIR}/.env"

log()  { echo "--- $*"; }
warn() { echo "WARNING: $*"; }
die()  { echo "ERROR: $*" >&2; exit 1; }

# ── Distro check ──────────────────────────────────────────────────────────────
check_distro() {
    local distro
    distro=$(lsb_release -si 2>/dev/null || echo "Unknown")
    if [[ "$distro" != "Raspbian" && "$distro" != "Debian" ]]; then
        warn "This script is designed for Raspberry Pi OS (Raspbian/Debian), got: $distro"
        read -rp "Proceed anyway? [y/N]: " proceed
        [[ "${proceed,,}" == y* ]] || { log "Exiting."; exit 1; }
    fi
}

# ── Docker ────────────────────────────────────────────────────────────────────
ensure_docker() {
    if ! command -v docker &>/dev/null; then
        log "Docker not found — installing via get.docker.com ..."
        curl -sSL https://get.docker.com | sh
        sudo usermod -aG docker "$USER"
        warn "Added $USER to the docker group."
        warn "If docker commands fail with permission errors, run: newgrp docker"
    else
        log "Docker: $(docker --version)"
    fi

    if ! docker compose version &>/dev/null; then
        die "docker compose plugin not found. Install Docker Engine 20.10+ which includes it."
    fi
    log "Docker Compose: $(docker compose version --short)"
}

# ── Chromium ──────────────────────────────────────────────────────────────────
ensure_chromium() {
    if ! command -v chromium &>/dev/null && ! command -v chromium-browser &>/dev/null; then
        log "Chromium not found — installing ..."
        sudo apt-get update -qq
        sudo apt-get install -y chromium
    else
        log "Chromium: OK"
    fi

    # kegbot-kiosk.service hardcodes /usr/bin/chromium
    if [[ ! -x /usr/bin/chromium ]]; then
        local found
        found=$(command -v chromium-browser 2>/dev/null || command -v chromium 2>/dev/null || true)
        if [[ -n "$found" && "$found" != "/usr/bin/chromium" ]]; then
            warn "Chromium is at $found, not /usr/bin/chromium."
            warn "The kiosk service ExecStart path may need to be updated in kegbot-kiosk.service."
        fi
    fi
}

# ── curl (needed for kiosk ExecStartPre health check) ─────────────────────────
ensure_curl() {
    if ! command -v curl &>/dev/null; then
        sudo apt-get update -qq
        sudo apt-get install -y curl
    fi
}

# ── Kegberry repo / deployment dir ────────────────────────────────────────────
setup_kegberry_dir() {
    if [[ -d "${KEGBERRY_DIR}/.git" ]]; then
        log "Updating kegberry repo at ${KEGBERRY_DIR} ..."
        git -C "${KEGBERRY_DIR}" pull
    elif [[ -f "${KEGBERRY_DIR}/docker-compose.yml" ]]; then
        log "${KEGBERRY_DIR} already has a docker-compose.yml — leaving as-is."
    else
        log "Cloning kegberry repo to ${KEGBERRY_DIR} ..."
        mkdir -p "$(dirname "${KEGBERRY_DIR}")"
        git clone "${KEGBERRY_REPO}" "${KEGBERRY_DIR}"
    fi
}

# ── Kegbot data directory ─────────────────────────────────────────────────────
setup_data_dir() {
    if [[ ! -d "${KEGBOT_DATA_DIR}" ]]; then
        log "Creating kegbot data dir at ${KEGBOT_DATA_DIR} ..."
        sudo mkdir -p "${KEGBOT_DATA_DIR}"
        sudo chmod 777 "${KEGBOT_DATA_DIR}"
    else
        log "Data dir ${KEGBOT_DATA_DIR}: OK"
    fi
}

# ── Generate .env (secrets + device) ─────────────────────────────────────────
setup_env() {
    if [[ -f "${ENV_FILE}" ]]; then
        log ".env already exists at ${ENV_FILE} — skipping secret generation."
        return
    fi

    log "Generating secrets ..."
    local secret_key api_key kegboard_device
    secret_key=$(tr -dc 'a-zA-Z0-9' </dev/urandom | fold -w 50 | head -n 1)
    api_key=$(tr -dc 'a-zA-Z0-9' </dev/urandom | fold -w 32 | head -n 1)

    # Auto-detect Arduino kegboard by USB serial ID
    local by_id_dir="/dev/serial/by-id"
    if ls "${by_id_dir}"/ 2>/dev/null | grep -qi arduino; then
        local dev_name
        dev_name=$(ls "${by_id_dir}"/ | grep -i arduino | head -n 1)
        kegboard_device="${by_id_dir}/${dev_name}"
        log "Detected kegboard device: ${kegboard_device}"
    else
        warn "No Arduino device found in ${by_id_dir}."
        warn "After plugging in the kegboard, edit ${ENV_FILE} and set KEGBOARD_DEVICE,"
        warn "then run: docker compose -f ${KEGBERRY_DIR}/docker-compose.yml up -d kegboard"
        kegboard_device="/dev/ttyACM0"
    fi

    cat > "${ENV_FILE}" <<EOF
# Generated by install.sh — do not commit this file
KEGBOT_SECRET_KEY=${secret_key}
KEGBOT_API_KEY=${api_key}
KEGBOARD_DEVICE=${kegboard_device}
EOF
    log "Wrote ${ENV_FILE}"
}

# ── Pull all images ───────────────────────────────────────────────────────────
pull_images() {
    log "Pulling images ..."
    docker pull ghcr.io/flangelo/kegbot-server:latest
    docker pull ghcr.io/flangelo/kegbot-pycore:latest
    docker pull mariadb:10.11
    docker pull redis:7.2
    docker pull nginx:alpine
}

# ── Start all services ────────────────────────────────────────────────────────
start_services() {
    log "Starting all services ..."
    docker compose -f "${KEGBERRY_DIR}/docker-compose.yml" --env-file "${ENV_FILE}" up -d
}

# ── Kiosk systemd service ─────────────────────────────────────────────────────
setup_kiosk_service() {
    local service_src="${KEGBERRY_DIR}/kegbot-kiosk.service"
    local service_dst="/etc/systemd/system/kegbot-kiosk.service"

    if [[ ! -f "${service_src}" ]]; then
        warn "kegbot-kiosk.service not found in ${KEGBERRY_DIR} — skipping kiosk setup."
        return
    fi

    log "Installing kiosk systemd service (User=${USER}) ..."
    sed "s/_KIOSK_USER_/${USER}/g" "${service_src}" | sudo tee "${service_dst}" > /dev/null
    sudo systemctl daemon-reload
    sudo systemctl enable kegbot-kiosk.service
    log "Kiosk service installed and enabled. It starts automatically with the graphical session."
}

# ── Main ──────────────────────────────────────────────────────────────────────
main() {
    check_distro
    ensure_curl
    ensure_docker
    ensure_chromium
    setup_kegberry_dir
    setup_data_dir
    setup_env
    pull_images
    start_services
    setup_kiosk_service

    echo ""
    log "Install complete!"
    echo ""
    echo "  Kegbot UI:  http://$(hostname):8000/"
    echo "  Logs:       docker logs -f kegberry-kegbot-1"
    echo ""

    if grep -q '/dev/ttyACM0' "${ENV_FILE}" && ! grep -q '/dev/serial/by-id/' "${ENV_FILE}"; then
        echo "NOTE: Kegboard USB device was not auto-detected."
        echo "      Plug in the Arduino, find the device with:"
        echo "        ls /dev/serial/by-id/"
        echo "      Then set KEGBOARD_DEVICE in ${ENV_FILE} and run:"
        echo "        docker compose -f ${KEGBERRY_DIR}/docker-compose.yml up -d kegboard"
        echo ""
    fi
}

main
